defmodule Helpcenter.Repo.TenantMigrations.UpdatedGroupPermissionIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:group_permissions, [:group_id, :resource, :action],
                     name: "group_permissions_unique_name_index"
                   )

    create unique_index(:group_permissions, [:group_id, :resource, :action],
             name: "group_permissions_unique_group_permission_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_permissions, [:group_id, :resource, :action],
                     name: "group_permissions_unique_group_permission_index"
                   )

    create unique_index(:group_permissions, [:group_id, :resource, :action],
             name: "group_permissions_unique_name_index"
           )
  end
end
