defmodule Helpcenter.Repo.TenantMigrations.AddProcessedAttributeToUserNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_notifications, prefix: prefix()) do
      add :processed, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:user_notifications, prefix: prefix()) do
      remove :processed
    end
  end
end
