defmodule Helpcenter.Repo.TenantMigrations.AddGroupsTable2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:groups), :action, to: :name

    rename table(:groups), :resource, to: :description

    alter table(:groups, prefix: prefix()) do
      modify :description, :text
      modify :name, :text
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    alter table(:groups, prefix: prefix()) do
      modify :action, :text
      modify :resource, :text
    end

    rename table(:groups), :description, to: :resource

    rename table(:groups), :name, to: :action
  end
end
