defmodule Helpcenter.Repo.TenantMigrations.AddAshParental do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments, prefix: prefix()) do
      add :parent_id,
          references(:comments,
            column: :id,
            name: "comments_parent_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:comments, "comments_parent_id_fkey")

    alter table(:comments, prefix: prefix()) do
      remove :parent_id
    end
  end
end
