defmodule Helpcenter.Repo.TenantMigrations.AddChildrenToCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories, prefix: prefix()) do
      add :parent_id, :uuid
    end
  end

  def down do
    alter table(:categories, prefix: prefix()) do
      remove :parent_id
    end
  end
end
