defmodule Helpcenter.Repo.Migrations.UpdatedArticleTagRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      remove :slug
    end

    alter table(:article_tags) do
      modify :tag_id, :uuid, null: true
      modify :article_id, :uuid, null: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:article_tags, [:article_id, :tag_id],
             name: "article_tags_unique_article_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:article_tags, [:article_id, :tag_id],
                     name: "article_tags_unique_article_tag_index"
                   )

    alter table(:article_tags) do
      remove :updated_at
      remove :inserted_at
      modify :article_id, :uuid, null: false
      modify :tag_id, :uuid, null: false
    end

    alter table(:tags) do
      add :slug, :text
    end
  end
end
