defmodule Helpcenter.Repo.Migrations.AddUserTeamsRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :current_team, :text
    end
  end

  def down do
    alter table(:users) do
      remove :current_team
    end
  end
end
