defmodule Helpcenter.Repo.Migrations.AddReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:articles) do
      modify :category_id, :uuid, null: true
    end
  end

  def down do
    alter table(:articles) do
      modify :category_id, :uuid, null: false
    end
  end
end
